### ISSUE TITLE
[Feature] Allow faded bars to only show on mouseover also in combat

### ISSUE THREAD

**Issue by deftanksfault** [GoldpawsStuff/AzeriteUI5#15]
### Is this issue for AzeriteUI for Dragonflight?

- [X] Yes, I understand. This is for Dragonflight.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I don't know if this is a bug or a feature, but it's something new compared to AzeriteUI 4 and previous versions of AzeriteUI 5 (<= 5.0.21-Beta). Faded bars are now displayed in combat, and faded out of combat.

### To reproduce

Type `/enablebarfade` then enter in combat.

### Expected behavior

Faded bars should remain faded, even if the player is in combat. If this is a new feature, it would be nice to have the option to display them or not during combat.

### Additional context

Version 5.0.22-Beta

**Comment by Scruffynerfherding** [comment]
One of the features in the original AzeriteUI (which I loved) was your faded bars would only become visible if you moused over them or in combat. I believe it was part of the "explorer mode" option. I loved that feature because when you weren't in combat, playing the game was so much more immersive because absolutely nothing would be on your HUD except the mini map. If you want them to only show up when moused over and not in combat, you can either wait till the full release (I'm assuming) or use Bartender. It pairs nicely with AzeritUI and allows to further customize your bar behavior. If you need some assistance figuring out, let me know.

**Comment by Goldpaw** [comment]
Well this is intentional, actually. Not a bug. 

The option to keep them faded in combat was not the default option in azui3. And what I've written so far for azui4/5, is based on the old default options. Meaning visible on mouseover AND combat! 

I will be adding options for this once I get a gui menu in place, though. And the options menu is right below the new editmode integration on my prio list. 

I'm changing this issue report to be a feature request, and renaming it to reflect for what! Then people coming here can see it's coming! :)

**Comment by Goldpaw** [comment]
Option only have faded bars visible on mouseover and not force them visible in combat is coming along with a lot of other options and an optionsmenu in 5.1.

**Comment by Goldpaw** [comment]
Added in 5.1.
