### ISSUE TITLE
[BUG] Moving minimap removes area information

### ISSUE THREAD

**Issue by shepard02** [GoldpawsStuff/AzeriteUI5#24]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I move the minimap away from its default position at the bottom, the area text and everything attached to it disappears.

### To reproduce

Just move the minimap to the top for example.

### Screenshots

![WoWScrnShot_042623_113504](https://user-images.githubusercontent.com/50554215/234536101-a3206a8b-3a2b-47fe-adce-dc55c6b2ab92.jpg)

### Additional context

More of a feature request: if the text didn't disappear, it would still be next to the minimap. It would be great if we could position it independently from the minimap, for example above or below it. Thanks.

**Comment by Goldpaw** [comment]
Not a bug. This is intentional. 

Do to the nature of how the area and performance information is displayed, it would look really strange when the minimap is placed anywhere but the bottom right corner of the screen. So until I can get some choices for those texts in place, we simply disable them when the minimap is moved.

**Comment by Goldpaw** [comment]
And I want to add, I do plan to add choices, so the zone/performance info can be shown and moved.

**Comment by shepard02** [comment]
Thank you for the reply and the info. Best ;)
