### ISSUE TITLE
[Feature] <Player Frame exact Mirror of Target Frame>

### ISSUE THREAD

**Issue by NuptupTDOW** [GoldpawsStuff/AzeriteUI5#62]
### Game Flavor

Wrath Classic, Classic Era

### Is there an existing request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I just want to see my character's face. :D

### Describe the solution you'd like

Currently the Player Frame shows a large Mana Bubble or Energy/resource Crystal instead of a Portrait of the character. I would like the option to modify it so that my Player Frame is _exactly_ the same as the Target Frame, Showing my character's portrait where the mana bubble would be, and then having a smaller resource crystal below the portrait. 

### Describe alternatives you've considered

Alternatively, I am personally not a huge fan of the mana bubble/resource crystal/small crystal that the target has anyway, and another option would simply be to allow the player to substitute those for an actual mana bar, which is easier to see at a glance roughly how much of that resource you or the target has. Additionally, this works very well in Classic Era to overlay a 5-second rule addon or weak aura to see the timer and regen ticks to save mana throughout a fight.

**Comment by Goldpaw** [comment]
This is available by enabling development mode with `/devmode` and then disabling the player unitframe from the `/azerite` menu. A second player frame entry will then magically appear in the unit listing on the left. 

This feature is sort of hidden because this new player frame isn't fully finished yet. It's functional and clickable but lacks pvp indicator, combat indicator and a few minor things like that. Going to close this issue though, as the feature now is in testing, and public.
