### ISSUE TITLE
[BUG] <title> LUA Error raised in world quests

### ISSUE THREAD

**Issue by wangyf0611** [GoldpawsStuff/AzeriteUI5#75]
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When enter a world quest area, a lua error raised.
This can be reproduced in every world quest in dragon flight maps.
I m using simplified Chinese wow client, not sure whether this is an i18n issue.
The game version is  11.0.2.56263.
Many thanks if can have a check.
![c08ee6c84e1b271b71183df5933aa70](https://github.com/user-attachments/assets/c7b93922-39a3-4674-88d1-f8bd2bb2431d)

=============8.28 update===============
hi, I noticed there is an alpha update in Azerite UI, fixing this issue and some others.
I tried to use this alpha version to test but failed.(game opening with a lot errors)
Here's what I did:
Download the addon from curseforge, and then replaced those changed files in recent commits,
such as wow11 related files, etc.

So I m wondering what is the suggested way to use and test the alpha version addon before it is released?
Many thanks again, very appreciate your work!
 

### To reproduce

step into a world quest area in Thaldraszus and this error will occur.

### Additional context

no more

**Comment by phlzZz** [comment]
I have the same problem

**Comment by Dimitar-Mitranov** [comment]
Hello There,

I have pretty much the same issue. 
![image](https://github.com/user-attachments/assets/e06855b7-845b-4e25-89b0-8f1847169866)
![image](https://github.com/user-attachments/assets/dcaf5265-fe31-4ba3-a1cf-49be1e5af5ad)

Seems connected to this from what I am able to perceive. From what I understand, AzriteUI is messing with the tracker itself.
When you go to Azerite's settings, we can see that there is a section added for quest tracker. I would assume that the developer is working to bring us a beautiful version of the objectives tracker. As I don't see the option to do anything right now, I would assume that it is experimental and in development phase. It's basically normal to have some issues, but much support to the developer and his masterful craft.

If it wasn't for Azerite I wouldn't have been playing Retail probably. Hoping for a quick and successful fix to this issue!

**Comment by Dimitar-Mitranov** [comment]
Hello to @phlzZz @wangyf0611 , I have managed to find a temporary fix to this issue. I think this is going to help you all until @Goldpaw works on this. I would assume he is very busy, so we can't expect him to fix this in a day or two, just because we have some minor issue. For that reason I will share what I found out. 

The easiest way to fix this issue is to get it once, get out of the bonus objective area, and then return to trigger the pop up again. The second time the pop up will appear normally, and minimize to the objective tracker to the right.

I was able to find some files connected to trackers, and tried to delete them and delete their lines in the xml files, located in @AzeriteUI/Components/Misc, but it didn't help.

I am not able to find the specific file that spews the error, and I can't search in the code of GoldPaw just to find where it is referenced. For that matter, I think that just letting this error appear once, then going out and in to fix it is more than enough as a solution for now. It takes 20-30 seconds to do, and you won't get this specific code during your session again.

It appears only anyways once you get to bonus objectives zones, so it isn't a big deal to begin with.

**Comment by wangyf0611** [comment]
hi @Dimitar-Mitranov , thanks to @PatTheMav in the PR https://github.com/GoldpawsStuff/AzeriteUI5/pull/83
with this solution the world quest issue can be solved permanently.
Since the PR is not merged yet, you can use my forked build result:
https://github.com/wangyf0611/AzeriteUI5/releases/download/5.2.183-Alpha-3/AzeriteUI-5.2.183-Alpha-3.zip
just replace the azerite ui folder and have fun :)

**Comment by Dimitar-Mitranov** [comment]
Thank you for sharing the Pull Request @wangyf0611, and for also providing the solution's download. Also big appreciation to PatTheMaw for creating the fix!

No more torment when doing world quests does feel nice!

**Comment by PadgeM** [comment]
Was this fixed? This just happened to me.
